import { inject } from '@angular/core';
import { CategoryService } from '../services/category-service';

// Category class
export class Category {
  _id: string | undefined; // Generated by the database
  value: number = 0;
  field: string = '';
  name: string = '';
  description: string = '';
  img: string = '';

  // Remove the _id before saving the Category
  removeBeforeSave(): Category {
    const ITEM = new Category();
    Object.assign(ITEM, this);
    delete ITEM._id;
    return ITEM;
  }
}

// Class to handle the category list
export class CategoryList {
  private categoryService = inject(CategoryService);
  private categories: Category[] = [];

  constructor() {
    // Retrieve all categories
    this.categoryService.getAllCategories().subscribe({
      next: (res: Category[]) => {
        this.categories = res;
      },
      error: (err: any) => {
        alert("Une erreur s'est produite lors de la récupération des données.");
        console.log(err);
      },
    });
  }

  // Returns the category list
  get items(): Category[] {
    return this.categories;
  }

  // Returns a category by its value
  getByValue(value: number): Category | undefined {
    return this.categories.find((category: Category) => category.value === value);
  }
}
