import { inject } from '@angular/core';
import { CountryService } from '../services/country-service';

// Country class
export class Country {
  _id: string | undefined; // Generated by the database
  value: number = 0;
  name: string = '';

  // Remove the _id before saving the Country
  removeBeforeSave(): Country {
    const ITEM = new Country();
    Object.assign(ITEM, this);
    delete ITEM._id;
    return ITEM;
  }
}

// Class to handle the country list
export class CountryList {
  private countryService = inject(CountryService);
  private countries: Country[] = [];

  constructor() {
    // Retrieve all countries
    this.countryService.getAllCountries().subscribe({
      next: (res: Country[]) => {
        this.countries = res;
      },
      error: (err: any) => {
        alert("Une erreur s'est produite lors de la récupération des données.");
        console.log(err);
      },
    });
  }

  // Returns the country list
  get items(): Country[] {
    return this.countries;
  }

  // Returns a country by its value
  getByValue(value: number): Country | undefined {
    return this.countries.find((country: Country) => country.value === value);
  }
}
