import { inject } from '@angular/core';
import { GenderService } from '../services/gender-service';

// Gender class
export class Gender {
  _id: string | undefined; // Generated by the database
  value: number = 0;
  field: string = '';
  name: string = '';

  // Remove the _id before saving the Gender
  removeBeforeSave(): Gender {
    const ITEM = new Gender();
    Object.assign(ITEM, this);
    delete ITEM._id;
    return ITEM;
  }
}

// Class to handle the gender list
export class GenderList {
  private genderService = inject(GenderService);
  private genders: Gender[] = [];

  constructor() {
    // Retrieve all genders
    this.genderService.getAllGenders().subscribe({
      next: (res: Gender[]) => {
        this.genders = res;
      },
      error: (err: any) => {
        alert("Une erreur s'est produite lors de la récupération des données.");
        console.log(err);
      },
    });
  }

  // Returns the gender list
  get items(): Gender[] {
    return this.genders;
  }

  // Returns a gender by its value
  getByValue(value: number): Gender | undefined {
    return this.genders.find((gender: Gender) => gender.value === value);
  }
}
