// Message class
export class Message {
  _id: string | undefined; // Generated by the database
  dateIns: Date | undefined; // Insertion date
  dateRep: Date | undefined; // Response date
  name: string = '';
  email: string = '';
  text: string = '';
  dateVisible: Date | undefined; // Date on which the data was show or hidden
  visible: boolean | undefined;

  // Temporary properties, not saved
  additional: any; // For additional properties (RxJS)

  // Remove these properties before saving the Message
  removeBeforeSave() {
    const ITEM = new Message();
    Object.assign(ITEM, this);
    delete ITEM._id;
    delete ITEM.dateIns;
    delete ITEM.dateRep;
    delete ITEM.dateVisible;
    delete ITEM.visible;
    delete ITEM.additional;
    return ITEM;
  }
}
