import { Common } from '../constants/common';
import { OrderProduct } from './order-product';
import { Cart } from './cart';

// Order class
export class Order {
  // Class properties
  _id: string | undefined; // Generated by the database
  reference: string = Common.getOrderRef();
  dateIns: Date | undefined; // Insertion date
  dateMod: Date | undefined; // Modification date
  userId: any; // The user ID or an object containing his information (using the 'populate' method on the server side)
  products: OrderProduct[] = [];
  promoCode: string = '';
  taxPercent: number = 0;
  promoPercent: number = 0;
  status: number = 0;
  dateVisible: Date | undefined; // Date on which the data was show or hidden
  visible: boolean | undefined;

  // Temporary property, not saved
  additional: any; // For additional properties (RxJS) while preserving the 'Order' type

  // Initialize the object, called when adding an order
  initialize(
    cart: Cart,
    taxPercent: number,
    promoCode: string | null = null,
    promoPercent: number | null = null,
  ): void {
    this.products = cart.products;
    this.taxPercent = taxPercent;

    if (typeof promoCode === 'string') {
      this.promoCode = promoCode;
      if (typeof promoPercent === 'number') this.promoPercent = promoPercent;
    }
  }

  // Returns the list of product IDs for the order
  getProductIDs(): string[] {
    return this.products.map((product: OrderProduct) => product.productId);
  }

  // Returns the total excluding tax
  getTotalExcludingTax(): number {
    const getTotal = (total: number, product: OrderProduct) => {
      return total + product.quantity * product.price;
    };
    return this.products.reduce(getTotal, 0);
  }

  // Returns the total including tax
  getTotalIncludingTax(): number {
    return (1 + this.taxPercent / 100) * this.getTotalExcludingTax();
  }

  // Returns the total including the promotion
  getTotalPromotion(): number {
    return (1 - this.promoPercent / 100) * this.getTotalIncludingTax();
  }

  // Retrieve the total invoiced price
  getTotalInvoiced(): number {
    return this.promoPercent > 0 ? this.getTotalPromotion() : this.getTotalIncludingTax();
  }

  // Update the status
  changeStatus(status: number): void {
    this.status = status;
  }

  // Remove these properties before saving the Order
  removeBeforeSave(): Order {
    const ITEM = new Order();
    Object.assign(ITEM, this);
    delete ITEM._id;
    delete ITEM.dateIns;
    delete ITEM.dateMod;
    delete ITEM.dateVisible;
    delete ITEM.visible;
    delete ITEM.additional;
    return ITEM;
  }
}
