import { Common } from '../constants/common';

// Object structuring the full description of a product
export type FullDesc = { title: string | undefined; description: Array<string> };

// Product class
export class Product {
  _id: string | undefined; // Generated by the database
  reference: string = Common.getProductRef();
  dateIns: Date | undefined; // Insertion date
  dateMod: Date | undefined; // Modification date
  userId: any; // The user ID or an object containing his information (using the 'populate' method on the server side)
  name: string = '';
  description: string = '';
  price: number = 0;
  stock: number = 0;
  img: string = '';
  types: number[] = [];
  categories: number[] = [];
  fullDescription: string = '';
  info: string = '';
  favorite: boolean = false;
  dateVisible: Date | undefined; // Date on which the data was show or hidden
  visible: boolean | undefined;

  // Temporary properties, not saved
  quantity: number | undefined = 0;
  additional: any; // For additional properties (RxJS) while preserving the 'Product' type

  // Remove these properties before saving the Product
  removeBeforeSave(): Product {
    const ITEM = new Product();
    Object.assign(ITEM, this);
    delete ITEM._id;
    delete ITEM.dateIns;
    delete ITEM.dateMod;
    delete ITEM.dateVisible;
    delete ITEM.visible;
    delete ITEM.quantity;
    delete ITEM.additional;
    return ITEM;
  }
}
