import { inject } from '@angular/core';
import { RoleService } from '../services/role-service';

// Role class
export class Role {
  _id: string | undefined; // Generated by the database
  value: number = 0;
  field: string = '';
  name: string = '';

  // Remove the _id before saving the Role
  removeBeforeSave(): Role {
    const ITEM = new Role();
    Object.assign(ITEM, this);
    delete ITEM._id;
    return ITEM;
  }
}

// Class to handle the role list
export class RoleList {
  private roleService = inject(RoleService);
  private roles: Role[] = [];

  constructor() {
    // Retrieve all roles
    this.roleService.getAllRoles().subscribe({
      next: (res: Role[]) => {
        this.roles = res;
      },
      error: (err: any) => {
        alert("Une erreur s'est produite lors de la récupération des données.");
        console.log(err);
      },
    });
  }

  // Returns the role list
  get items(): Role[] {
    return this.roles;
  }

  // Returns a role by its value
  getByValue(value: number): Role | undefined {
    return this.roles.find((role: Role) => role.value === value);
  }
}
