import { inject } from '@angular/core';
import { StatusService } from '../services/status-service';

// Status class
export class Status {
  _id: string | undefined; // Generated by the database
  value: number = 0;
  field: string = '';
  name: string = '';

  // Remove the _id before saving the Status
  removeBeforeSave(): Status {
    const ITEM = new Status();
    Object.assign(ITEM, this);
    delete ITEM._id;
    return ITEM;
  }
}

// Class to handle the status list
export class StatusList {
  private statusService = inject(StatusService);
  private status: Status[] = [];

  constructor() {
    // Retrieve all status
    this.statusService.getAllStatus().subscribe({
      next: (res: Status[]) => {
        this.status = res;
      },
      error: (err: any) => {
        alert("Une erreur s'est produite lors de la récupération des données.");
        console.log(err);
      },
    });
  }

  // Returns the status list
  get items(): Status[] {
    return this.status;
  }

  // Returns a status by its value
  getByValue(value: number): Status | undefined {
    return this.status.find((status: Status) => status.value === value);
  }
}
