import { Common } from '../constants/common';

// Object containing the data allowing a user to log in
export type LoginData = { email: string; pswd: string };

// Token returned by the backend
export type Token = { token: string };

// Token payload after decoding
export class TokenPayload {
  // User informations
  id: string = '';
  name: string = '';
  role: number = 0;
}

// User class
export class User {
  _id: string | undefined; // Generated by the database
  reference: string = Common.getUserRef();
  dateIns: Date | undefined; // Insertion date
  dateMod: Date | undefined; // Modification date
  name: string = '';
  email: string = '';
  pswd: string = '';
  gender: number = 0;
  interests: number[] = [];
  country: number = 0;
  role: number = 0;
  dateVisible: Date | undefined; // Date on which the data was show or hidden
  visible: boolean | undefined;

  // Temporary property, not saved
  additional: any; // For additional properties (RxJS) while preserving the 'User' type

  // Remove these properties before saving the User
  removeBeforeSave(): User {
    const ITEM = new User();
    Object.assign(ITEM, this);
    delete ITEM._id;
    delete ITEM.dateIns;
    delete ITEM.dateMod;
    delete ITEM.dateVisible;
    delete ITEM.visible;
    delete ITEM.additional;
    return ITEM;
  }
}
